### ISSUE TITLE
please remove peter griffin

### ISSUE THREAD

**Issue by erions55** [VueKo7/sitoNapoli#2]
_please remove_ **peter griffin**
https://images-ext-2.discordapp.net/external/Aos3O5IH0JrvJNW07_Gm8GxCBaIVpv2rYkvDvoSbNK8/https/media.tenor.com/orppG1DLLssAAAPo/peter-griffin.mp4

**Comment by Olly06** [comment]
![peter-griffin-zak-site it-15012024](https://github.com/VueKo7/sitoNapoli/assets/106401904/2782098a-4fbf-4815-91f8-43d21dbb3282)
